name: Check

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

jobs:
    check:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                task: [ detekt, spotlessKotlinCheck ]
        steps:
            -   uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
            -   name: Set up JDK 11
                uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3
                with:
                    distribution: "temurin"
                    java-version: 11
            -   name: Check ${{ matrix.task }}
                run: ./gradlew ${{ matrix.task }}
